name: notes_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/main_body.jpg
    - assets/images/notas_body.jpg


flutter_launcher_icons:
  image_path: "assets/icons/easy_notes_icon.png"
  android: true 
  ios: true 
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"